name: Docker Build/Publish Image 
on:  
  push:    
    branches: [ master ]  
jobs:   
  build:    
    runs-on: ubuntu-latest    
    env:      
      DOCKER_REGISTRY:
      DOCKER_IMAGE: kharex/ez-ipupdate
      DOCKER_TARGET_PLATFORM: linux/amd64,linux/arm64,linux/arm/v7                 
    steps:    
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Prepare
      if: success()
      id: prepare
      run: | 
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM} 
        echo ::set-output name=docker_image::${DOCKER_IMAGE} 
        echo ::set-output name=version::${GITHUB_RUN_NUMBER} 
    - name: Login to Docker Hub
      if: success()
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      if: success()
      uses: docker/build-push-action@v2
      with: 
        context: .
        platforms: ${{ steps.prepare.outputs.docker_platform }}
        push: true
        tags: ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}, ${{ steps.prepare.outputs.docker_image }}:latest
